# Generated by Django 3.2.13 on 2022-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('birthplace', models.CharField(choices=[('JL', '전라도'), ('CC', '충청도'), ('JJ', '제주도'), ('GW', '강원도'), ('GS', '경상도')], default='CC', max_length=2)),
            ],
        ),
    ]
